name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.483'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install Barge
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/barge
        # ref: tags/dex-2019-10-09
        ref: develop
        path: barge
    - name: Start Barge
      run: |
        cd ../barge
        sudo sysctl -w vm.max_map_count=262144
        ./start_ocean.sh --no-brizo --no-surfer --no-koi --local-spree-node &
        sleep 240
    - name: Wait for barge startup
      run: scripts/wait_for_migration_and_extract_keeper_artifacts.sh
    - name: Install Surfer
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/surfer
        ref: develop
        path: surfer
    - name : Start Surfer
      run: |
        cd ../surfer
        clojure -M:main &
        sleep 30
    - name: Test
      run: |
        pip install pytest
        pytest
